version: "3.9"
services:
  ws-blogs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ws-blogs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped